include classpath("application.conf")

# Address and port for the SQS-compatible interface
rest-sqs {
	enabled = true
	bind-port = 9324
	bind-hostname = "0.0.0.0"
}

# Define queues
queues = {
	user_events {
	  defaultVisibilityTimeout = 30 seconds
	  delay = 0 seconds
	  receiveMessageWait = 0 seconds
	}
}