
#user  nobody;
worker_processes  10;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;


events {
    worker_connections  1024;
}


http {
  include       mime.types;
  default_type application/json;
  charset utf-8;

  sendfile        on;
  keepalive_timeout  65;

  upstream auth_service {
    server localhost:4000;
  }

  upstream user_service {
    server localhost:4001;
  }

  upstream chat_service {
    server localhost:4002;
  }

  server {
    listen 8080;

    location /api/auth/ {
      proxy_pass http://auth_service;
    }

    location /api/users/ {
      proxy_pass http://user_service;
    }

    location /api/chats/ {
      proxy_pass http://chat_service;
    }
	
	location /socket/ {
	  proxy_pass http://chat_service/socket/;
	  proxy_http_version 1.1;
	  proxy_set_header Upgrade $http_upgrade;
	  proxy_set_header Connection "upgrade";
	}
  }
 
}
